global:
  scrape_interval:     5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:1212']

  ### node-exporter
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:1515']

  ### cadvisor
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.17.0.1:10321' ]


#        ### Postgres-exporter
#  - job_name: 'postgres-exporter'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['172.17.0.1:5432']
